server:
  port: 4002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lostandfound
    username: jjj
    password: jjj
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  #mvc:
  #  static-path-pattern: /**


  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
