server:
  port: 5002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lostandfound
    username: jjj
    password: jjj
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**/templates

  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
